apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: basic-user-pass-docker
  namespace: tekton-pipelines
spec:
  encryptedData:
    password: AgAl9SdLNoMQaau+lpUwWT7vPNunPJMovLLcbrKvMYU5kpNPh0qoq+QnCYzR/rIgzv5fk7wxkgUi6moStzLoR7t1XAbnj0h7VAS4TV64oehc1rAJQw2w/HsSU9DvT8IAPP6I02xTnBZaEjjnjH3ro+fAMiyZqyJphmMYGH+rDVum5fSzPENtOJ+CJYKNklwrrcZjvzrvJgmP/02nNDzAJq69ZAvR54i2aEroDXvoQrAvMl/l97vQSDs6nhxs6VJzpw6sfOkIT0DjkHW6bGD98KQ1TUz5svTaIk7K0k/GcYGzVM/9GCMr7vutRxg/pw2MD3kAJ6BIwTtGe97kzlALwj8a837pMCk9mGGPLf2Zym56b1b3RcBALNOqnH+GLhttnz5AglJqJs1psjunuJtZJJZhyy/B8LcErnHLefGyNaquE2GBQ/JNIu0jL07G+bOpMRi66q+A3pmmvwLm0T65uiJoCZrtVs2ZfhhEMuhrMhAXMoh2nWbM1Cp4bKvRQIps81XV5RxCEFNakdN1TWFT2c9/snYOnqWBKmCoUOnxdWQZGfPsPRG1eDeLXO0Pwo5yAIVDGeu6AytoVNukCj0dmQ4Eah+i6+hXlkRt9U45Bq+Il/0/6sGzELB0KzMI6djwlnZRqByd9BBRM04RbV825VvOL09n7+AGfK79xBU82pr3T1tlXawa2AZ12Ge1KnhjC//3av1ZU1p3IhFhG0WTahBs
    username: AgAW3K1rB1qIdebAABEdroNwL/4R8puX/BfELRhe2e3Y2lXWlYkdkULUkXJNwl+KIbdg18AFEwaZjlGRb4rSDSgW3AFl/NjbrYmPUvi9l8PAGJaNzx9MRTYvsI5Ao+Z81Yd/yeLmuoj0ZtE5LYDe5I2GNoPgMOJRn9tUpH+uD5CdYQnzOM1rXIUxz04H/RWbjjk0qfzsckqw6bjnMMY1noGUhr9L6teaHf2zchRnpIzSFzk7g4dyXO96GCThthqU9idfjqrlrNdbko1JqdIVluoj1cMSHblbQJoygWOFdcV0FsSh6eLbZjI2rqNfVdSHw6u/hHOBvAn943ErP+Cwwm+lGt3DM4C12rzj1CEKzYpvl8VDOhN5uCngPTW+6o5r4kgxJUuLorNvIEsA9N0anclBttZpE13ChYYE8KwiUJ57C0ygyKCnxNpB/6q0P8+G8bmfP4thYFij4HGRE+xFSdZ80gHMFVOHQJeLckD7fu1cvgAXE6k166Wsuf9OTm+8+j5zwJWLHwFgf7sGhYaK5nrXwsT0nYgGRO0IY0zveZwSOCXomz94DNW4TvzGz4+Ab+3rEwSwRl/nxfmpB3AiQ/rTpxXCShUQ24UkLYSo2nZ+RvBi3VDXIHsJVTK9dCZUZzTLKu1DxXimRU1ozDkbDb9hKRMzcj8Qq43Bpp6TrLH5tNY/FqY1/CWLCqU+oUFtJJm445ekfoY=
  template:
    data: null
    metadata:
      annotations:
        tekton.dev/docker-0: https://index.docker.io
      creationTimestamp: null
      name: basic-user-pass-docker
      namespace: tekton-pipelines
    type: kubernetes.io/basic-auth
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: argocd-env-secret
  namespace: tekton-pipelines
spec:
  encryptedData:
    ARGOCD_PASSWORD: AgBZBDLMn1MJZXnF+UHxl+4tn/kwKCUJJQTBbyfRl8sGG0MZxAS+hoI5WVB4ZJSYicwvJCiu3AEB5mSOfDPm1Y+kszjXA/8rwnGikWX6HyuRPgL08KHGgo0/t9/EJaRLeIg1uy1jLWolz/H+AQo6t6ncOAVgFAjyRsSuAECBWg8Km8pDt39RIVYWbRxz2CIqWzQNvEDQd9k9k1rMcKFZKsSPJ4jFlR4Nw+s8zVeGxVc+f5t+jvJt75iV2K0bx4hMaZFhZfHFeTUVHqkx17sbqeFqqlHSdDZ5xUfZfIN51cS+LNDaLtekbQJt6QpYfUBoS9d+6+ECMUEWSq18xBgqQs8bjG5KtOI9XQQK2/Z/KWjbaQhGorzz7oMo5dvalK93BzP8YNVLb8HGGDokxQ13197qGL8IDdjpyw9uSp4P937PpqgjNWrq7eqGlRBTykXjYKzF/UDE50DuXFAPiwprjDdvnsseAD1uwt5oV+6eD4V7Yz34JXX7bNK+EG/aOgMKdSJnbfToGtviICHdFpzxuwN2Pylxw2Ko5WTqzyfk2/eBfO/S49Fa+ITRN2dMa5bGtdrEbVjCQnvpgusBQ1sVK9AOxgoNZjdEbHEmP9kKPY5/pqrJJfUxFZuihYq6Dsje+VbQ5b1zj04SXknSnOXsaxK4n4cgeBwuoDIItQrfQvYALOPe7ZLtifGKc8ARxJR/3H0LKIEGc/6X8lGbpcF0vEml
    ARGOCD_USERNAME: AgBOslxaSFJ7RJPCh/XPpg0dpWWyPK/qwhoj9Ulip0silXu2jScoNtob5UbMKSuiItdKP9S4QSqvp2j8AUm/4VF5fpkaskS6+zRj/fMmifY3mfHcSyi5kLbZV7EWVP7X6u6y3oTRNrlKuAeSHoo//QeRU7Kg7vieTxOSU7A4WjaiqBBvGcyYSzLV9wKMd/AfnVn4z/UDHfIwq3yH5SQRddsEuTH88qPgiNcavmuyDrw27SumYFGUb6m6vKRVfINGfatjI4dTU2OpkO6g1ZZltnBYZVq1jwUH8L/ylXOV71Qip+B+qYW+0twZ4EsyfLxav/e70oHnTA3xx+DoA7X2YCq+BhEiW6QK+xymhi68jSB8Hh9DdjSFFCW95sf47qZUL20KGzVGiDENwf9hnOEgbpcugdIp3+atcd497onuEy5OoJbrlwahs87HpcKzsNOdnC1I3W/CKrFF4Owl6Sx9oAvVYJ//HXcD6fijh3bv+7joQEChANQJEqkQ8sxFckFaVk/zJfrRZLBr91XpdYcmcAkM49VUFdpDdrJHVkFsvtW816evKu2TU9f625t6FwvKFAmf4D/vly0GkFMULe9GZhCP3dQWCaNPZ1/k+me/VV7r1Ver/0NghE9vZcwSdFvB3eE3RWTHLQ0iZc7Aoqmbll0r7Epibo96BVmjwilUo30dsXnZfKn4dnRNGPscI6YKJPeSHS4TKg==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: argocd-env-secret
      namespace: tekton-pipelines
