apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-dns
# namePrefix: prod-
resources:
- ../../base
- external-crd-dnsendpoint.yaml
- external-crd-dnsendpoint-test.yaml
- external-dns-deployment.yaml
- external-dns-objects.yaml
- sealed_secrets.yaml
