apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-play-dns-update
  namespace: external-dns
spec:
  encryptedData:
    access-key-id: AgBacUo0kOWV2ERnTtxABxUByJwVif4lvGMroGjbEN3ALYLzD+dQMN68k+Zw2ppzqlMC7CndezIJN8+7EonJABSSe+KFpYC3uPJ+4maG59GYr5zqlYNkGu1vuAbbeYeEGMa1rLSxv61N+g9Ee9B/o8xBh868wsKKuhv1mXsSLObuhxSGIGmHEiGKDfbUGhb/It/trEx0A6MWZkbUV9sbPmyke/COwO0SMQlYNNXGpQz6+arK1XUpaCnUsn6/W4M2/+aHaARsiVjXbHRIk9bDoNFIaDmbCDzjV+J8MFWWQ65qF3d5n7sE+n3Yn27QkRq4osj1MdoKdKaUExcOS+tXF8qhtlF+J0F+5RyzlQiCIMDxdberXB65gmVqB8/uZNzREp3wiFHI4vtNr1MI7LhHu7IjX+WHgLfS3F7W/XZezWLOiDbDfuGuKJcbVvipsxj5dbEB61JqfnC01Gnw5n6oXSgb4lKGEsqt7+IwIGjC0ElVy4fY/PjlA/za0O5LdWjqTHvfsOtxhH7/zTSSI5Dy+RGW5JsMVzkojSmVtsHxYMO7hIIlkalrFxAZrLyjpHjD7F1O6rVreWn+vxZ5wBqDdUr5Irh3pOodS13ZYCDmjpm/5Ingvc81vp4fQXviEeZFVg2yrYPa953o7P3wvDqPUjOoiEwI7B0dM5m1FquoQoZF5qOUi5mV5fDhxTgVSQoBMsiRUcFjXnMS0qMW+e4AyJxy+5EjDQ==
    secret-access-key: AgAZXjhVfsSZoV9OnR8uejwI9yD6ZsgSJGuXu1wAOfyBeDxAfgHmWgkALvrywO2ormpxNNv1rWsW3Vt1p0m3ir7dHhk0lYPYuVQlsOVvARyznKHtdq7ojoEyuSpUgT/pU5RHiOYob+9VwA3dOAAEsDzAmYrYtRtzrhtOLKvyKFTRUiaioTydiXYtqzu/QVfDRPxvw2EXRRE5f5Y7sAziPOqBRabrHq056/8VrSV0OrhPEq5tQDhjGPTEk52CpvtD3G+SfMVjP73rjS1p65CLKyA7cuMoxtr/SBVf5SAyho24ohE1ddKPGFmKXqcNQgI+p+oqcCx/15FBCJ5At/QzTnsPMhUHfOGxRixzOWbqcyeC1pWzMf0uw57GaFHbYpGxTI6SrVZ1rCS4SbK7MQas6mWPGagHGgnHCzArNIYkB8Bx37rvkeFTDIyQJ5Nj3CFkjt78hsdnWnd3CQsPBdKr5sYTUdy5wdW/X5WXovhYqVgGLumbjxw4Q0VbxYf7q0I6bMkYQPHWY1aKcihi8BbpJIUwtR10AL51vZtLy2kk2JA4KJaAduL7X1Iy9mPSsEd5OcCcmVp4z0/9Sp2dE6+Gdczp2enVnqmNx7ECv7fPqoZGf5gtOnC/mfjk7ovcbKzzKiLvZiDxbPNa23I3yGkLUINrWee83MGQPpnaybXeUML5hN6IcK9TBNDQnfiax0UbzDR6V7va2cUtHmmTh+zl/uCfB376BR4mXz8tWo/YCFYfokZROTvQ7Q2b
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-play-dns-update
      namespace: external-dns
    type: Opaque
