apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tekton-pipelines
# namePrefix: prod-
resources:
- release.yaml
- interceptors.yaml
- ingress.yaml
- serviceaccount.yaml
- sealed_secrets.yaml
- rbac.yaml
- pvc.yaml
patches:
  - target:
      version: v1
      kind: Ingress
      name: el-github-event-listener
    patch: |-
      - op: add
        path: "/metadata/annotations/external-dns.alpha.kubernetes.io~1hostname"
        value: tekton-webhook.play.p2o.be
      - op: replace
        path: "/spec/rules/0/host"
        value: tekton-webhook.play.p2o.be
